const CharecterActions = {
    GET_CHARECTERS : 'GET_CHARECTERS',
    GET_CHARECTERS_WITH_PAGINATION: 'GET_CHARECTERS_WITH_PAGINATION',
    GET_CHARECTERS_SUCCESS : 'GET_CHARECTERS_SUCCESS',
    SEARCH_CHARECTER: 'SEARCH_CHARECTER',
    SEARCH_CHARECTER_SUCCESS: 'SEARCH_CHARECTER_SUCCESS',
    NO_MATCH_FOUND: 'NO_MATCH_FOUND',
    GET_CHARECTER_COMICS: 'GET_CHARECTER_COMICS',
    GET_CHARECTER_COMICS_SUCCESS: 'GET_CHARECTER_COMICS_SUCCESS',
}

export default CharecterActions;