const CharecterActions = {
    GET_CHARECTERS : 'GET_CHARECTERS',
    SEARCH_CHARECTER: 'SEARCH_CHARECTER',
    SEARCH_CHARECTER_SUCCESS: 'SEARCH_CHARECTER_SUCCESS',
    NO_MATCH_FOUND: 'NO_MATCH_FOUND'
}

export default CharecterActions;